In [1]:
import numpy as np

In [2]:
# Create a 2D array of shape 5x3 to contain 20 random decimal numbers between -10 and 10
arr = np.random.randint(-10, 10, (5, 3))

In [3]:
print(arr)

[[ -2  -8  -3]
 [  4  -1  -6]
 [  4 -10  -7]
 [  0  -2   7]
 [  2  -1  -7]]


In [10]:
def f(A):
    A[A < 0] = 0
    A[A > 0] = 1
    return A
f(arr)
print(arr)

[[0 0 0]
 [1 0 0]
 [1 0 0]
 [0 0 1]
 [1 0 0]]
